
services:
  server-dev:
    build:
      context: .
      dockerfile: infra/server/Dockerfile
    container_name: distributed_log_server
    volumes:
      - .:/app
    ports:
      - "2222:22"
      - "9999:9999/udp"
      - "8080:8080"
    privileged: true

